name: Auto Generate README for All Repos

on:
  schedule:
    - cron: '0 0 * * *' # Runs once a day; adjust this as needed
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-readmes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Ensure full checkout

    - name: Debug Current Directory and Files
      run: |
        pwd
        ls -R # List all files to ensure scripts exist and are accessible
        
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Use your preferred Python version

    - name: Install Dependencies
      run: |
        pip install google.generativeai  # Install all required dependencies
        
    - name: Fetch All Repositories
      id: repos
      run: |
        curl -H "Authorization: token ${{ secrets.PAT }}" \
        https://api.github.com/user/repos?per_page=100 \
        > repos.json
        echo "Repos fetched: $(jq '.[] | .name' repos.json)"
        
    - name: Loop Through Repositories and Generate README
      run: |
        python3 ${{ github.workspace }}/scripts/generate_readmes.py
          
    - name: Commit and Push README to Each Repo
      run: |
        python3 ${{ github.workspace }}/scripts/commit_readmes.py
